{{- if .Values.forwarder.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ach-forwarder
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ach.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: forwarder
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ach-forwarder
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ach.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: forwarder
spec:
  replicas: {{ .Values.forwarder.replicas | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: ach
      app.kubernetes.io/component: forwarder
  template:
    metadata:
      labels:
        {{- include "ach.commonLabels" . | nindent 8 }}
        app.kubernetes.io/component: forwarder
    spec:
      serviceAccountName: ach-forwarder
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: forwarder
          image: {{ include "ach.image" . }}
          imagePullPolicy: {{ include "ach.imagePullPolicy" . }}
          args: {{ toYaml .Values.forwarder.args | nindent 12 }}
          ports:
            - name: healthz
              containerPort: 8081
          env:
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources: {{ toYaml .Values.forwarder.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
{{- end }}
