---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ach-forwarder-role-binding
  namespace: system
  labels:
    app.kubernetes.io/name: ach
    app.kubernetes.io/component: forwarder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ach-forwarder-role
subjects:
- kind: ServiceAccount
  name: ach-forwarder
  namespace: system
