apiVersion: ach.ackstorm.ai/v1alpha1
kind: PluginMarketplace
metadata:
  labels:
    app.kubernetes.io/name: ach
    app.kubernetes.io/managed-by: kustomize
  name: pluginmarketplace-sample
  namespace: ach-system
spec: {}
