apiVersion: ach.ackstorm.ai/v1alpha1
kind: Artifact
metadata:
  labels:
    app.kubernetes.io/name: ach
    app.kubernetes.io/managed-by: kustomize
  name: example-artifact
  namespace: ach-system
spec:
  type: s3
  scope: directory
  s3:
    bucket: ach-example-bucket
    key: artifacts/customer-kb/
    region: us-east-1
    authSecretRef:
      name: ach-example-s3
      accessKeyIdKey: accessKeyId
      secretAccessKeyKey: secretAccessKey
  refresh:
    interval: 1h
    maxStaleness: 12h
