apiVersion: ach.ackstorm.ai/v1alpha1
kind: PluginMarketplace
metadata:
  labels:
    app.kubernetes.io/name: ach
    app.kubernetes.io/managed-by: kustomize
  name: example-marketplace
  namespace: ach-system
spec:
  type: github
  github:
    repo: ackstorm/ach-marketplace
    ref: main
    authSecretRef:
      name: github-readonly
      key: access-key
  refresh:
    interval: 1h
    maxStaleness: 24h
