apiVersion: ach.ackstorm.ai/v1alpha1
kind: Environment
metadata:
  labels:
    app.kubernetes.io/name: ach
    app.kubernetes.io/managed-by: kustomize
  name: example
  namespace: ach-system
spec:
  authorizedTeams:
    - default
  notice: |
    This environment works best with the openai-* models.
    Remember to re-login after rotating your keys.
  runtime:
    models: []
    mcpServers: []
    a2aAgents: []
  context:
    prompts: []
    plugins: []
    artifacts: []
