apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPRemoteProxy
metadata:
  name: deepwiki-rproxy
  namespace: mcp
spec:
  remoteURL: https://mcp.deepwiki.com/mcp
  transport: streamable-http
  oidcConfig:
    type: inline
    inline:
      issuer: http://dex.dex-system.svc.cluster.local:5556/dex
      audience: mcp:deepwiki
      insecureAllowHTTP: true
      jwksUrl: http://dex.dex-system.svc.cluster.local:5556/dex/keys
