apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: aws-documentation
  namespace: mcp
spec:
  image: ghcr.io/astral-sh/uv:alpine
  args:
    - uvx
    - awslabs.aws-documentation-mcp-server@latest
  env:
  - name: AWS_DOCUMENTATION_PARTITION
    value: aws
  - name: UV_CACHE_DIR
    value: /tmp/uv-cache
  transport: stdio
  proxyMode: streamable-http  
  podTemplateSpec:
    spec:
      containers:
      - name: mcp
        securityContext:
          readOnlyRootFilesystem: false
          runAsNonRoot: false 
