// SPDX-License-Identifier: Apache-2.0

// emit.go ships the structured audit-event payload (Event) and the
// EmitAudit helper that every Phase 3 handler calls to write a single
// audit record through the Phase 2 audit logger
// (internal/audit/handler.go NewLogger). The helper centralizes the
// §18.2 schema → slog-attribute translation so handlers do not
// re-derive it.

package audit

import (
	"context"
	"log/slog"
)

// Event is the structured audit-event payload Phase 3 handlers compose
// before calling EmitAudit. The shape binds Hub §18.2 verbatim:
//
//   - Action — one of the Action* constants in events.go (closed enum).
//   - Outcome — one of the Outcome* constants in events.go (closed enum).
//   - Actor — "<namespace>/<sso-email>" per Hub §18.3 / Specifics block.
//     Handlers compose this from os.Getenv("POD_NAMESPACE") (downward
//     API) + keyCtx.OwnerEmail. SSO-callback failures pre-resolution
//     pass "<namespace>/-".
//   - RequestID — "req_<ulid>" generated by the RequestID middleware
//     (D-02 step 1) and propagated through context.Context.
//   - KeyID — "pkid_..." or "ekid_..." form (Hub §18.2). NEVER the
//     plaintext credential value; NEVER a credential_hash. Optional —
//     empty string omits the attribute (events like SSO state-mismatch
//     do not have a resolved key_id yet).
//   - Target — optional; resource-scoped events MUST populate it
//     (Environment lifecycle, EK create/revoke, etc.). Nil omits both
//     target.kind and target.name.
//   - Environment — G20 first-class governance dimension: the resolved
//     Environment name the request operated under (hydrate envName,
//     ek row environment, content-bound env). Optional — empty omits the
//     "environment" attribute. Promoted out of Extra so dashboards and
//     access policies can key on it directly.
//   - SourceIP / UserAgent — G20 first-class forensics: the client
//     RemoteAddr (preferring the first X-Forwarded-For hop) and the
//     User-Agent header, captured by middleware. Optional — empty omits.
//   - Route — G20 first-class: the chi route pattern the request matched
//     (e.g. "/platform/hydrate"). Optional — empty omits.
//   - Extra — optional additional context attributes (e.g. "team":
//     "default" on the SSO-default-team-missing branch). MUST NOT
//     carry plaintext, credential_hash, response bodies, or raw error
//     strings (see audit-safety contract on EmitAudit).
//
// D-19: Event is composed at the HANDLER site, never by middleware.
// The handler retains control over the resolved key.id (with the
// pkid_/ekid_ prefix) and the target.kind / target.name pairing so the
// composition stays auditable at code review.
type Event struct {
	Action      string
	Outcome     string
	Actor       string
	RequestID   string
	KeyID       string
	Target      *Target
	Environment string // G20: first-class governance dimension
	SourceIP    string // G20: forensics (RemoteAddr / X-Forwarded-For)
	UserAgent   string // G20: forensics
	Route       string // G20: request route (chi RoutePattern)
	Extra       map[string]string
}

// Target is the resource a request operated on. Kind is a stable
// vocabulary string ("environment", "plugin", "litellm_key", "user");
// Name is the CR metadata.name or the LiteLLM token id (the latter
// preserves the Phase 2 orphan-cleanup target.name convention so
// pre-Phase-3 audit lines remain comparable).
type Target struct {
	Kind string
	Name string
}

// EmitAudit writes a single structured audit record through logger.
// logger must be a *slog.Logger constructed by audit.NewLogger so the
// audit=true top-level predicate is already attached.
//
// The function:
//
//   - Uses e.Action as the slog message AND as a top-level "action"
//     attribute. The double-coding is intentional (matches the Phase 2
//     orphan-loop idiom — r.Audit.Info("operator.orphan-cleanup", ...,
//     "outcome", X)) so both message-based and attribute-based log
//     filters work.
//   - Omits the "key.id" attribute when e.KeyID == "".
//   - Omits both "target.kind" and "target.name" attributes when
//     e.Target is nil.
//   - Appends every k/v pair in e.Extra. Map iteration order is
//     non-deterministic but slog records are matched by attribute
//     name, not order, downstream.
//   - ctx is currently unused but kept in the signature for future
//     context-derived attributes (trace_id, span_id, request-scope
//     deadline). Callers SHOULD pass r.Context() so wiring is in
//     place when those attributes are added.
//
// Audit-safety contract (referenced from audit/doc.go +
// .planning/phases/03-hub-identity-platform-api/03-CONTEXT.md D-19):
// callers MUST NOT pass credential plaintext (e.g. "pk_...", "ek_..."),
// credential_hash values, response bodies, or raw error strings as
// attribute values inside e.Extra (or e.KeyID, e.Actor, etc.). The
// helper transports the values raw — it does NOT scrub. The contract
// is enforced by handler-plan code review (03-07..03-10), not by this
// function. The
// [feedback_litellm_operator_no_redaction_filter] memory pattern
// applies: discipline over scrubbing.
func EmitAudit(ctx context.Context, logger *slog.Logger, e Event) {
	_ = ctx // reserved for future ctx-derived attributes (trace_id, etc.)

	// 4 always-present attributes × 2 slots each = 8 capacity floor;
	// pre-size for key.id (2) + target.* (4) + the 4 G20 fields (8) +
	// headroom for Extra.
	attrs := make([]any, 0, 8+2+4+8+2*len(e.Extra))
	attrs = append(attrs,
		"action", e.Action,
		"outcome", e.Outcome,
		"actor", e.Actor,
		"request_id", e.RequestID,
	)
	if e.KeyID != "" {
		attrs = append(attrs, "key.id", e.KeyID)
	}
	if e.Target != nil {
		attrs = append(attrs, "target.kind", e.Target.Kind, "target.name", e.Target.Name)
	}
	// G20 first-class fields — each omitted when empty (mirrors key.id).
	if e.Environment != "" {
		attrs = append(attrs, "environment", e.Environment)
	}
	if e.SourceIP != "" {
		attrs = append(attrs, "source.ip", e.SourceIP)
	}
	if e.UserAgent != "" {
		attrs = append(attrs, "source.user_agent", e.UserAgent)
	}
	if e.Route != "" {
		attrs = append(attrs, "route", e.Route)
	}
	for k, v := range e.Extra {
		attrs = append(attrs, k, v)
	}

	logger.Info(e.Action, attrs...)
}
